spring:
  application:
    name: candy-factory-timesheet
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        default_schema: heroku_17980cdde1af860

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.url}
    password: ${email.password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
